################################################################################################################################################################

# @project        Library/Mathematics
# @file           .travis.yml
# @author         Lucas Brémond <lucas@loftorbital.com>
# @license        TBD

################################################################################################################################################################

branches:

    only:

        - /^\d+\.\d+(\.\d+)?(-\S*)?$/
        - master
        - dev

os:

    - linux

sudo: false

services:

    - docker

language: cpp

env:

    global:

        - LANG="en_US.UTF-8"

stages:

    - test
    - coverage
    - name: deploy
      if: tag =~ ^\d+\.\d+(\.\d+)?(-\S*)?$

jobs:

    include:

        - stage: test

          script:

                # Pull Docker image from repository
                
                - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
                - docker pull openspacecollective/library-mathematics:latest || true

                # Run tests

                - ./tools/ci/test.sh

        - stage: coverage
        
          script:

                # Pull Docker image from repository
                
                - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
                - docker pull openspacecollective/library-mathematics:latest || true

                # Run coverage

                - ./tools/ci/coverage.sh
        
        - stage: deploy

          script:

                # Pull Docker image from repository
                
                - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
                - docker pull openspacecollective/library-mathematics:latest || true

                # Generate and deploy documentation

                - ./tools/ci/documentation.sh

                # Generate and deploy binaries

                - ./tools/ci/binaries.sh

          before_deploy:

                - echo "Deploying binaries to GitHub Releases..."

          deploy:

                provider: releases
                api_key: ${GITHUB_API_KEY}
                file_glob: true
                file:
                    - ./bin/*
                    - ./lib/*
                skip_cleanup: true
                on:
                    branch: master
                    tags: true

################################################################################################################################################################